/*
 * nexo retailer API
 * API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: romain.loreal@lorealconsulting.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lorealconsulting.nexoRetailerAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lorealconsulting.nexoRetailerAPI.client.model.PoipoiIdfinancialServiceServiceRequestEnvironmentCardPlainCardData;
import com.lorealconsulting.nexoRetailerAPI.client.model.PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardData;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Payment card performing the transaction.&lt;br/&gt;
 */
@Schema(description = "Payment card performing the transaction.<br/>")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-09T14:21:17.741236018+02:00[Europe/Paris]")

public class PoipoiIdfinancialServiceServiceRequestEnvironmentCard {
  @SerializedName("AdditionalCardData")
  private Object additionalCardData = null;

  @SerializedName("AllowedProduct")
  private Object allowedProduct = null;

  @SerializedName("CardBrand")
  private Object cardBrand = null;

  @SerializedName("CardCurrencyCode")
  private Object cardCurrencyCode = null;

  @SerializedName("CardCountryCode")
  private Object cardCountryCode = null;

  @SerializedName("CardProductProfile")
  private Object cardProductProfile = null;

  @SerializedName("CardProductSubType")
  private Object cardProductSubType = null;

  @SerializedName("CardProductType")
  private Object cardProductType = null;

  @SerializedName("InternationalCard")
  private Object internationalCard = null;

  @SerializedName("IssuerBIN")
  private Object issuerBIN = null;

  @SerializedName("MaskedPAN")
  private Object maskedPAN = null;

  @SerializedName("PlainCardData")
  private PoipoiIdfinancialServiceServiceRequestEnvironmentCardPlainCardData plainCardData = null;

  @SerializedName("PaymentAccountReference")
  private Object paymentAccountReference = null;

  @SerializedName("ProtectedCardData")
  private PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardData protectedCardData = null;

  @SerializedName("PrivateCardData")
  private Object privateCardData = null;

  @SerializedName("ServiceOption")
  private Object serviceOption = null;

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard additionalCardData(Object additionalCardData) {
    this.additionalCardData = additionalCardData;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 70characters.&lt;br/&gt;
   * @return additionalCardData
  **/
  @Schema(description = "Specifies a character string with a maximum length of 70characters.<br/>")
  public Object getAdditionalCardData() {
    return additionalCardData;
  }

  public void setAdditionalCardData(Object additionalCardData) {
    this.additionalCardData = additionalCardData;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard allowedProduct(Object allowedProduct) {
    this.allowedProduct = allowedProduct;
    return this;
  }

   /**
   * Product that can be purchased with the card.
   * @return allowedProduct
  **/
  @Schema(description = "Product that can be purchased with the card.")
  public Object getAllowedProduct() {
    return allowedProduct;
  }

  public void setAllowedProduct(Object allowedProduct) {
    this.allowedProduct = allowedProduct;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard cardBrand(Object cardBrand) {
    this.cardBrand = cardBrand;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 35 characters.&lt;br/&gt;
   * @return cardBrand
  **/
  @Schema(description = "Specifies a character string with a maximum length of 35 characters.<br/>")
  public Object getCardBrand() {
    return cardBrand;
  }

  public void setCardBrand(Object cardBrand) {
    this.cardBrand = cardBrand;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard cardCurrencyCode(Object cardCurrencyCode) {
    this.cardCurrencyCode = cardCurrencyCode;
    return this;
  }

   /**
   * Specifies an alphanumeric string with a length of exact 3 characters.&lt;br/&gt;
   * @return cardCurrencyCode
  **/
  @Schema(description = "Specifies an alphanumeric string with a length of exact 3 characters.<br/>")
  public Object getCardCurrencyCode() {
    return cardCurrencyCode;
  }

  public void setCardCurrencyCode(Object cardCurrencyCode) {
    this.cardCurrencyCode = cardCurrencyCode;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard cardCountryCode(Object cardCountryCode) {
    this.cardCountryCode = cardCountryCode;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 3 characters.&lt;br/&gt;
   * @return cardCountryCode
  **/
  @Schema(description = "Specifies a character string with a maximum length of 3 characters.<br/>")
  public Object getCardCountryCode() {
    return cardCountryCode;
  }

  public void setCardCountryCode(Object cardCountryCode) {
    this.cardCountryCode = cardCountryCode;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard cardProductProfile(Object cardProductProfile) {
    this.cardProductProfile = cardProductProfile;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 35 characters.&lt;br/&gt;
   * @return cardProductProfile
  **/
  @Schema(description = "Specifies a character string with a maximum length of 35 characters.<br/>")
  public Object getCardProductProfile() {
    return cardProductProfile;
  }

  public void setCardProductProfile(Object cardProductProfile) {
    this.cardProductProfile = cardProductProfile;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard cardProductSubType(Object cardProductSubType) {
    this.cardProductSubType = cardProductSubType;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 35 characters.&lt;br/&gt;
   * @return cardProductSubType
  **/
  @Schema(description = "Specifies a character string with a maximum length of 35 characters.<br/>")
  public Object getCardProductSubType() {
    return cardProductSubType;
  }

  public void setCardProductSubType(Object cardProductSubType) {
    this.cardProductSubType = cardProductSubType;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard cardProductType(Object cardProductType) {
    this.cardProductType = cardProductType;
    return this;
  }

   /**
   * Type of card product.&lt;br/&gt;- **COMM: CommercialCard**  : *Cards issued as a means of business expenditure, for instance business card or corporate card. The user could be a company, an individual for business expenses or a self employed for business purposes.*&lt;br/&gt;- **CONS: ConsumerCard**  : *Cards issued as a means of personal expenditure. The user is always an individual.*&lt;br/&gt;
   * @return cardProductType
  **/
  @Schema(description = "Type of card product.<br/>- **COMM: CommercialCard**  : *Cards issued as a means of business expenditure, for instance business card or corporate card. The user could be a company, an individual for business expenses or a self employed for business purposes.*<br/>- **CONS: ConsumerCard**  : *Cards issued as a means of personal expenditure. The user is always an individual.*<br/>")
  public Object getCardProductType() {
    return cardProductType;
  }

  public void setCardProductType(Object cardProductType) {
    this.cardProductType = cardProductType;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard internationalCard(Object internationalCard) {
    this.internationalCard = internationalCard;
    return this;
  }

   /**
   * A flag indicating a True or False value.&lt;br/&gt;
   * @return internationalCard
  **/
  @Schema(description = "A flag indicating a True or False value.<br/>")
  public Object getInternationalCard() {
    return internationalCard;
  }

  public void setInternationalCard(Object internationalCard) {
    this.internationalCard = internationalCard;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard issuerBIN(Object issuerBIN) {
    this.issuerBIN = issuerBIN;
    return this;
  }

   /**
   * Specifies a numeric string with a maximum length of 15 digits.&lt;br/&gt;
   * @return issuerBIN
  **/
  @Schema(description = "Specifies a numeric string with a maximum length of 15 digits.<br/>")
  public Object getIssuerBIN() {
    return issuerBIN;
  }

  public void setIssuerBIN(Object issuerBIN) {
    this.issuerBIN = issuerBIN;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard maskedPAN(Object maskedPAN) {
    this.maskedPAN = maskedPAN;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 30 characters.&lt;br/&gt;
   * @return maskedPAN
  **/
  @Schema(description = "Specifies a character string with a maximum length of 30 characters.<br/>")
  public Object getMaskedPAN() {
    return maskedPAN;
  }

  public void setMaskedPAN(Object maskedPAN) {
    this.maskedPAN = maskedPAN;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard plainCardData(PoipoiIdfinancialServiceServiceRequestEnvironmentCardPlainCardData plainCardData) {
    this.plainCardData = plainCardData;
    return this;
  }

   /**
   * Get plainCardData
   * @return plainCardData
  **/
  @Schema(description = "")
  public PoipoiIdfinancialServiceServiceRequestEnvironmentCardPlainCardData getPlainCardData() {
    return plainCardData;
  }

  public void setPlainCardData(PoipoiIdfinancialServiceServiceRequestEnvironmentCardPlainCardData plainCardData) {
    this.plainCardData = plainCardData;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard paymentAccountReference(Object paymentAccountReference) {
    this.paymentAccountReference = paymentAccountReference;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 70characters.&lt;br/&gt;
   * @return paymentAccountReference
  **/
  @Schema(description = "Specifies a character string with a maximum length of 70characters.<br/>")
  public Object getPaymentAccountReference() {
    return paymentAccountReference;
  }

  public void setPaymentAccountReference(Object paymentAccountReference) {
    this.paymentAccountReference = paymentAccountReference;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard protectedCardData(PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardData protectedCardData) {
    this.protectedCardData = protectedCardData;
    return this;
  }

   /**
   * Get protectedCardData
   * @return protectedCardData
  **/
  @Schema(description = "")
  public PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardData getProtectedCardData() {
    return protectedCardData;
  }

  public void setProtectedCardData(PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardData protectedCardData) {
    this.protectedCardData = protectedCardData;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard privateCardData(Object privateCardData) {
    this.privateCardData = privateCardData;
    return this;
  }

   /**
   * Binary data of 100K maximum.&lt;br/&gt;
   * @return privateCardData
  **/
  @Schema(description = "Binary data of 100K maximum.<br/>")
  public Object getPrivateCardData() {
    return privateCardData;
  }

  public void setPrivateCardData(Object privateCardData) {
    this.privateCardData = privateCardData;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCard serviceOption(Object serviceOption) {
    this.serviceOption = serviceOption;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 35 characters.&lt;br/&gt;
   * @return serviceOption
  **/
  @Schema(description = "Specifies a character string with a maximum length of 35 characters.<br/>")
  public Object getServiceOption() {
    return serviceOption;
  }

  public void setServiceOption(Object serviceOption) {
    this.serviceOption = serviceOption;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoipoiIdfinancialServiceServiceRequestEnvironmentCard poipoiIdfinancialServiceServiceRequestEnvironmentCard = (PoipoiIdfinancialServiceServiceRequestEnvironmentCard) o;
    return Objects.equals(this.additionalCardData, poipoiIdfinancialServiceServiceRequestEnvironmentCard.additionalCardData) &&
        Objects.equals(this.allowedProduct, poipoiIdfinancialServiceServiceRequestEnvironmentCard.allowedProduct) &&
        Objects.equals(this.cardBrand, poipoiIdfinancialServiceServiceRequestEnvironmentCard.cardBrand) &&
        Objects.equals(this.cardCurrencyCode, poipoiIdfinancialServiceServiceRequestEnvironmentCard.cardCurrencyCode) &&
        Objects.equals(this.cardCountryCode, poipoiIdfinancialServiceServiceRequestEnvironmentCard.cardCountryCode) &&
        Objects.equals(this.cardProductProfile, poipoiIdfinancialServiceServiceRequestEnvironmentCard.cardProductProfile) &&
        Objects.equals(this.cardProductSubType, poipoiIdfinancialServiceServiceRequestEnvironmentCard.cardProductSubType) &&
        Objects.equals(this.cardProductType, poipoiIdfinancialServiceServiceRequestEnvironmentCard.cardProductType) &&
        Objects.equals(this.internationalCard, poipoiIdfinancialServiceServiceRequestEnvironmentCard.internationalCard) &&
        Objects.equals(this.issuerBIN, poipoiIdfinancialServiceServiceRequestEnvironmentCard.issuerBIN) &&
        Objects.equals(this.maskedPAN, poipoiIdfinancialServiceServiceRequestEnvironmentCard.maskedPAN) &&
        Objects.equals(this.plainCardData, poipoiIdfinancialServiceServiceRequestEnvironmentCard.plainCardData) &&
        Objects.equals(this.paymentAccountReference, poipoiIdfinancialServiceServiceRequestEnvironmentCard.paymentAccountReference) &&
        Objects.equals(this.protectedCardData, poipoiIdfinancialServiceServiceRequestEnvironmentCard.protectedCardData) &&
        Objects.equals(this.privateCardData, poipoiIdfinancialServiceServiceRequestEnvironmentCard.privateCardData) &&
        Objects.equals(this.serviceOption, poipoiIdfinancialServiceServiceRequestEnvironmentCard.serviceOption);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalCardData, allowedProduct, cardBrand, cardCurrencyCode, cardCountryCode, cardProductProfile, cardProductSubType, cardProductType, internationalCard, issuerBIN, maskedPAN, plainCardData, paymentAccountReference, protectedCardData, privateCardData, serviceOption);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoipoiIdfinancialServiceServiceRequestEnvironmentCard {\n");
    
    sb.append("    additionalCardData: ").append(toIndentedString(additionalCardData)).append("\n");
    sb.append("    allowedProduct: ").append(toIndentedString(allowedProduct)).append("\n");
    sb.append("    cardBrand: ").append(toIndentedString(cardBrand)).append("\n");
    sb.append("    cardCurrencyCode: ").append(toIndentedString(cardCurrencyCode)).append("\n");
    sb.append("    cardCountryCode: ").append(toIndentedString(cardCountryCode)).append("\n");
    sb.append("    cardProductProfile: ").append(toIndentedString(cardProductProfile)).append("\n");
    sb.append("    cardProductSubType: ").append(toIndentedString(cardProductSubType)).append("\n");
    sb.append("    cardProductType: ").append(toIndentedString(cardProductType)).append("\n");
    sb.append("    internationalCard: ").append(toIndentedString(internationalCard)).append("\n");
    sb.append("    issuerBIN: ").append(toIndentedString(issuerBIN)).append("\n");
    sb.append("    maskedPAN: ").append(toIndentedString(maskedPAN)).append("\n");
    sb.append("    plainCardData: ").append(toIndentedString(plainCardData)).append("\n");
    sb.append("    paymentAccountReference: ").append(toIndentedString(paymentAccountReference)).append("\n");
    sb.append("    protectedCardData: ").append(toIndentedString(protectedCardData)).append("\n");
    sb.append("    privateCardData: ").append(toIndentedString(privateCardData)).append("\n");
    sb.append("    serviceOption: ").append(toIndentedString(serviceOption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
