/*
 * nexo retailer API
 * API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: romain.loreal@lorealconsulting.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lorealconsulting.nexoRetailerAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Location on the Earth specified by the Universal Transverse Mercator coordinate system.  Identifies the geographic location using the WGS84 ellipsoid spatial reference system.&lt;br/&gt;
 */
@Schema(description = "Location on the Earth specified by the Universal Transverse Mercator coordinate system.  Identifies the geographic location using the WGS84 ellipsoid spatial reference system.<br/>")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-09T14:21:17.741236018+02:00[Europe/Paris]")

public class PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates {
  @SerializedName("UTMEastward")
  private Object utMEastward = null;

  @SerializedName("UTMNorthward")
  private Object utMNorthward = null;

  @SerializedName("UTMZone")
  private Object utMZone = null;

  public PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates utMEastward(Object utMEastward) {
    this.utMEastward = utMEastward;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 35 characters.&lt;br/&gt;
   * @return utMEastward
  **/
  @Schema(required = true, description = "Specifies a character string with a maximum length of 35 characters.<br/>")
  public Object getUtMEastward() {
    return utMEastward;
  }

  public void setUtMEastward(Object utMEastward) {
    this.utMEastward = utMEastward;
  }

  public PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates utMNorthward(Object utMNorthward) {
    this.utMNorthward = utMNorthward;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 35 characters.&lt;br/&gt;
   * @return utMNorthward
  **/
  @Schema(required = true, description = "Specifies a character string with a maximum length of 35 characters.<br/>")
  public Object getUtMNorthward() {
    return utMNorthward;
  }

  public void setUtMNorthward(Object utMNorthward) {
    this.utMNorthward = utMNorthward;
  }

  public PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates utMZone(Object utMZone) {
    this.utMZone = utMZone;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 35 characters.&lt;br/&gt;
   * @return utMZone
  **/
  @Schema(required = true, description = "Specifies a character string with a maximum length of 35 characters.<br/>")
  public Object getUtMZone() {
    return utMZone;
  }

  public void setUtMZone(Object utMZone) {
    this.utMZone = utMZone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates poipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates = (PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates) o;
    return Objects.equals(this.utMEastward, poipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates.utMEastward) &&
        Objects.equals(this.utMNorthward, poipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates.utMNorthward) &&
        Objects.equals(this.utMZone, poipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates.utMZone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(utMEastward, utMNorthward, utMZone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationUTMCoordinates {\n");
    
    sb.append("    utMEastward: ").append(toIndentedString(utMEastward)).append("\n");
    sb.append("    utMNorthward: ").append(toIndentedString(utMNorthward)).append("\n");
    sb.append("    utMZone: ").append(toIndentedString(utMZone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
