/*
 * nexo retailer API
 * API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: romain.loreal@lorealconsulting.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lorealconsulting.nexoRetailerAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lorealconsulting.nexoRetailerAPI.client.model.PoipoiIdfinancialServiceHeaderInitiatingParty;
import com.lorealconsulting.nexoRetailerAPI.client.model.PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Point of interaction (POI) performing the transaction.&lt;br/&gt;
 */
@Schema(description = "Point of interaction (POI) performing the transaction.<br/>")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-09T14:21:17.741236018+02:00[Europe/Paris]")

public class PoipoiIdfinancialServiceServiceRequestEnvironmentPOI {
  @SerializedName("Component")
  private Object component = null;

  @SerializedName("Capabilities")
  private PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities capabilities = null;

  @SerializedName("GroupIdentification")
  private Object groupIdentification = null;

  @SerializedName("Identification")
  private PoipoiIdfinancialServiceHeaderInitiatingParty identification = null;

  @SerializedName("SystemName")
  private Object systemName = null;

  @SerializedName("TerminalIntegration")
  private Object terminalIntegration = null;

  @SerializedName("TimeZone")
  private Object timeZone = null;

  public PoipoiIdfinancialServiceServiceRequestEnvironmentPOI component(Object component) {
    this.component = component;
    return this;
  }

   /**
   * Data related to a component of the POI (Point Of Interaction) performing the transaction.
   * @return component
  **/
  @Schema(description = "Data related to a component of the POI (Point Of Interaction) performing the transaction.")
  public Object getComponent() {
    return component;
  }

  public void setComponent(Object component) {
    this.component = component;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentPOI capabilities(PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities capabilities) {
    this.capabilities = capabilities;
    return this;
  }

   /**
   * Get capabilities
   * @return capabilities
  **/
  @Schema(description = "")
  public PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities getCapabilities() {
    return capabilities;
  }

  public void setCapabilities(PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities capabilities) {
    this.capabilities = capabilities;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentPOI groupIdentification(Object groupIdentification) {
    this.groupIdentification = groupIdentification;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 35 characters.&lt;br/&gt;
   * @return groupIdentification
  **/
  @Schema(description = "Specifies a character string with a maximum length of 35 characters.<br/>")
  public Object getGroupIdentification() {
    return groupIdentification;
  }

  public void setGroupIdentification(Object groupIdentification) {
    this.groupIdentification = groupIdentification;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentPOI identification(PoipoiIdfinancialServiceHeaderInitiatingParty identification) {
    this.identification = identification;
    return this;
  }

   /**
   * Get identification
   * @return identification
  **/
  @Schema(required = true, description = "")
  public PoipoiIdfinancialServiceHeaderInitiatingParty getIdentification() {
    return identification;
  }

  public void setIdentification(PoipoiIdfinancialServiceHeaderInitiatingParty identification) {
    this.identification = identification;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentPOI systemName(Object systemName) {
    this.systemName = systemName;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 70characters.&lt;br/&gt;
   * @return systemName
  **/
  @Schema(description = "Specifies a character string with a maximum length of 70characters.<br/>")
  public Object getSystemName() {
    return systemName;
  }

  public void setSystemName(Object systemName) {
    this.systemName = systemName;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentPOI terminalIntegration(Object terminalIntegration) {
    this.terminalIntegration = terminalIntegration;
    return this;
  }

   /**
   * Indicates the type of integration of the POI terminal in the sale environment.&lt;br/&gt;- **INDR: Indoor**  : *Indoor terminal.*&lt;br/&gt;- **IPMP: InsidePump**  : *Terminal incorporated in the pump dispensing petrol.*&lt;br/&gt;- **MPOI: MultiplePOITerminal**  : *Multiple terminals linked to a unique sale terminal.*&lt;br/&gt;- **MPMP: MultiplePump**  : *Outdoor terminal serving several petrol pumps.*&lt;br/&gt;- **MSLE: MultipleSaleTerminal**  : *Terminal serving multiple sale terminals.*&lt;br/&gt;- **SSLE: SingleSaleTerminal**  : *Terminal linked to a unique sale terminal.*&lt;br/&gt;- **VNDG: VendingMachine**  : *Terminal integrated in a vending machine.*&lt;br/&gt;
   * @return terminalIntegration
  **/
  @Schema(description = "Indicates the type of integration of the POI terminal in the sale environment.<br/>- **INDR: Indoor**  : *Indoor terminal.*<br/>- **IPMP: InsidePump**  : *Terminal incorporated in the pump dispensing petrol.*<br/>- **MPOI: MultiplePOITerminal**  : *Multiple terminals linked to a unique sale terminal.*<br/>- **MPMP: MultiplePump**  : *Outdoor terminal serving several petrol pumps.*<br/>- **MSLE: MultipleSaleTerminal**  : *Terminal serving multiple sale terminals.*<br/>- **SSLE: SingleSaleTerminal**  : *Terminal linked to a unique sale terminal.*<br/>- **VNDG: VendingMachine**  : *Terminal integrated in a vending machine.*<br/>")
  public Object getTerminalIntegration() {
    return terminalIntegration;
  }

  public void setTerminalIntegration(Object terminalIntegration) {
    this.terminalIntegration = terminalIntegration;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentPOI timeZone(Object timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 70characters.&lt;br/&gt;
   * @return timeZone
  **/
  @Schema(description = "Specifies a character string with a maximum length of 70characters.<br/>")
  public Object getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(Object timeZone) {
    this.timeZone = timeZone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoipoiIdfinancialServiceServiceRequestEnvironmentPOI poipoiIdfinancialServiceServiceRequestEnvironmentPOI = (PoipoiIdfinancialServiceServiceRequestEnvironmentPOI) o;
    return Objects.equals(this.component, poipoiIdfinancialServiceServiceRequestEnvironmentPOI.component) &&
        Objects.equals(this.capabilities, poipoiIdfinancialServiceServiceRequestEnvironmentPOI.capabilities) &&
        Objects.equals(this.groupIdentification, poipoiIdfinancialServiceServiceRequestEnvironmentPOI.groupIdentification) &&
        Objects.equals(this.identification, poipoiIdfinancialServiceServiceRequestEnvironmentPOI.identification) &&
        Objects.equals(this.systemName, poipoiIdfinancialServiceServiceRequestEnvironmentPOI.systemName) &&
        Objects.equals(this.terminalIntegration, poipoiIdfinancialServiceServiceRequestEnvironmentPOI.terminalIntegration) &&
        Objects.equals(this.timeZone, poipoiIdfinancialServiceServiceRequestEnvironmentPOI.timeZone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(component, capabilities, groupIdentification, identification, systemName, terminalIntegration, timeZone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoipoiIdfinancialServiceServiceRequestEnvironmentPOI {\n");
    
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    groupIdentification: ").append(toIndentedString(groupIdentification)).append("\n");
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    systemName: ").append(toIndentedString(systemName)).append("\n");
    sb.append("    terminalIntegration: ").append(toIndentedString(terminalIntegration)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
