/*
 * nexo retailer API
 * API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: romain.loreal@lorealconsulting.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lorealconsulting.nexoRetailerAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lorealconsulting.nexoRetailerAPI.client.model.PoipoiIdfinancialServiceServiceRequestContextDirectDebitContext;
import com.lorealconsulting.nexoRetailerAPI.client.model.PoipoiIdfinancialServiceServiceRequestContextPaymentContext;
import com.lorealconsulting.nexoRetailerAPI.client.model.PoipoiIdfinancialServiceServiceRequestContextSaleContext;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Context in which the transaction is performed (payment and sale).&lt;br/&gt;
 */
@Schema(description = "Context in which the transaction is performed (payment and sale).<br/>")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-09T14:21:17.741236018+02:00[Europe/Paris]")

public class PoipoiIdfinancialServiceServiceRequestContext {
  @SerializedName("DirectDebitContext")
  private PoipoiIdfinancialServiceServiceRequestContextDirectDebitContext directDebitContext = null;

  @SerializedName("PaymentContext")
  private PoipoiIdfinancialServiceServiceRequestContextPaymentContext paymentContext = null;

  @SerializedName("SaleContext")
  private PoipoiIdfinancialServiceServiceRequestContextSaleContext saleContext = null;

  public PoipoiIdfinancialServiceServiceRequestContext directDebitContext(PoipoiIdfinancialServiceServiceRequestContextDirectDebitContext directDebitContext) {
    this.directDebitContext = directDebitContext;
    return this;
  }

   /**
   * Get directDebitContext
   * @return directDebitContext
  **/
  @Schema(description = "")
  public PoipoiIdfinancialServiceServiceRequestContextDirectDebitContext getDirectDebitContext() {
    return directDebitContext;
  }

  public void setDirectDebitContext(PoipoiIdfinancialServiceServiceRequestContextDirectDebitContext directDebitContext) {
    this.directDebitContext = directDebitContext;
  }

  public PoipoiIdfinancialServiceServiceRequestContext paymentContext(PoipoiIdfinancialServiceServiceRequestContextPaymentContext paymentContext) {
    this.paymentContext = paymentContext;
    return this;
  }

   /**
   * Get paymentContext
   * @return paymentContext
  **/
  @Schema(description = "")
  public PoipoiIdfinancialServiceServiceRequestContextPaymentContext getPaymentContext() {
    return paymentContext;
  }

  public void setPaymentContext(PoipoiIdfinancialServiceServiceRequestContextPaymentContext paymentContext) {
    this.paymentContext = paymentContext;
  }

  public PoipoiIdfinancialServiceServiceRequestContext saleContext(PoipoiIdfinancialServiceServiceRequestContextSaleContext saleContext) {
    this.saleContext = saleContext;
    return this;
  }

   /**
   * Get saleContext
   * @return saleContext
  **/
  @Schema(description = "")
  public PoipoiIdfinancialServiceServiceRequestContextSaleContext getSaleContext() {
    return saleContext;
  }

  public void setSaleContext(PoipoiIdfinancialServiceServiceRequestContextSaleContext saleContext) {
    this.saleContext = saleContext;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoipoiIdfinancialServiceServiceRequestContext poipoiIdfinancialServiceServiceRequestContext = (PoipoiIdfinancialServiceServiceRequestContext) o;
    return Objects.equals(this.directDebitContext, poipoiIdfinancialServiceServiceRequestContext.directDebitContext) &&
        Objects.equals(this.paymentContext, poipoiIdfinancialServiceServiceRequestContext.paymentContext) &&
        Objects.equals(this.saleContext, poipoiIdfinancialServiceServiceRequestContext.saleContext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(directDebitContext, paymentContext, saleContext);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoipoiIdfinancialServiceServiceRequestContext {\n");
    
    sb.append("    directDebitContext: ").append(toIndentedString(directDebitContext)).append("\n");
    sb.append("    paymentContext: ").append(toIndentedString(paymentContext)).append("\n");
    sb.append("    saleContext: ").append(toIndentedString(saleContext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
