/*
 * nexo retailer API
 * API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: romain.loreal@lorealconsulting.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lorealconsulting.nexoRetailerAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Location on the Earth specified by two numbers representing vertical and horizontal position.&lt;br/&gt;
 */
@Schema(description = "Location on the Earth specified by two numbers representing vertical and horizontal position.<br/>")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-09T14:21:17.741236018+02:00[Europe/Paris]")

public class PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationGeographicCoordinates {
  @SerializedName("Latitude")
  private Object latitude = null;

  @SerializedName("Longitude")
  private Object longitude = null;

  public PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationGeographicCoordinates latitude(Object latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 35 characters.&lt;br/&gt;
   * @return latitude
  **/
  @Schema(required = true, description = "Specifies a character string with a maximum length of 35 characters.<br/>")
  public Object getLatitude() {
    return latitude;
  }

  public void setLatitude(Object latitude) {
    this.latitude = latitude;
  }

  public PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationGeographicCoordinates longitude(Object longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Specifies a character string with a maximum length of 35 characters.&lt;br/&gt;
   * @return longitude
  **/
  @Schema(required = true, description = "Specifies a character string with a maximum length of 35 characters.<br/>")
  public Object getLongitude() {
    return longitude;
  }

  public void setLongitude(Object longitude) {
    this.longitude = longitude;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationGeographicCoordinates poipoiIdfinancialServiceHeaderInitiatingPartyGeolocationGeographicCoordinates = (PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationGeographicCoordinates) o;
    return Objects.equals(this.latitude, poipoiIdfinancialServiceHeaderInitiatingPartyGeolocationGeographicCoordinates.latitude) &&
        Objects.equals(this.longitude, poipoiIdfinancialServiceHeaderInitiatingPartyGeolocationGeographicCoordinates.longitude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(latitude, longitude);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoipoiIdfinancialServiceHeaderInitiatingPartyGeolocationGeographicCoordinates {\n");
    
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
