/*
 * nexo retailer API
 * API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: romain.loreal@lorealconsulting.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lorealconsulting.nexoRetailerAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Parameters associated to a cryptographic encryption algorithm.&lt;br/&gt;
 */
@Schema(description = "Parameters associated to a cryptographic encryption algorithm.<br/>")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-09T14:21:17.741236018+02:00[Europe/Paris]")

public class PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter {
  @SerializedName("BytePadding")
  private Object bytePadding = null;

  @SerializedName("InitialisationVector")
  private Object initialisationVector = null;

  @SerializedName("EncryptionFormat")
  private Object encryptionFormat = null;

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter bytePadding(Object bytePadding) {
    this.bytePadding = bytePadding;
    return this;
  }

   /**
   * Byte padding for a cypher block chaining mode encryption, if the padding is not implicit.&lt;br/&gt;- **LNGT: LengthPadding**  : *Message to encrypt is completed by a byte value containing the total number of added bytes.*&lt;br/&gt;- **NUL8: Null80Padding**  : *Message to encrypt is completed by one bit of value 1, followed by null bits until the encryption block length is reached.*&lt;br/&gt;- **NULG: NullLengthPadding**  : *Message to encrypt is completed by null byte values, the last byte containing the total number of added bytes.*&lt;br/&gt;- **NULL: NullPadding**  : *Message to encrypt is completed by null bytes.*&lt;br/&gt;- **RAND: RandomPadding**  : *Message to encrypt is completed by random value, the last byte containing the total number of added bytes.*&lt;br/&gt;
   * @return bytePadding
  **/
  @Schema(description = "Byte padding for a cypher block chaining mode encryption, if the padding is not implicit.<br/>- **LNGT: LengthPadding**  : *Message to encrypt is completed by a byte value containing the total number of added bytes.*<br/>- **NUL8: Null80Padding**  : *Message to encrypt is completed by one bit of value 1, followed by null bits until the encryption block length is reached.*<br/>- **NULG: NullLengthPadding**  : *Message to encrypt is completed by null byte values, the last byte containing the total number of added bytes.*<br/>- **NULL: NullPadding**  : *Message to encrypt is completed by null bytes.*<br/>- **RAND: RandomPadding**  : *Message to encrypt is completed by random value, the last byte containing the total number of added bytes.*<br/>")
  public Object getBytePadding() {
    return bytePadding;
  }

  public void setBytePadding(Object bytePadding) {
    this.bytePadding = bytePadding;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter initialisationVector(Object initialisationVector) {
    this.initialisationVector = initialisationVector;
    return this;
  }

   /**
   * Specifies a binary string with a maximum length of 500 binary bytes.&lt;br/&gt;
   * @return initialisationVector
  **/
  @Schema(description = "Specifies a binary string with a maximum length of 500 binary bytes.<br/>")
  public Object getInitialisationVector() {
    return initialisationVector;
  }

  public void setInitialisationVector(Object initialisationVector) {
    this.initialisationVector = initialisationVector;
  }

  public PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter encryptionFormat(Object encryptionFormat) {
    this.encryptionFormat = encryptionFormat;
    return this;
  }

   /**
   * Format of data before encryption, if the format is not plaintext or implicit.&lt;br/&gt;- **TR31: TR31**  : *Format of a cryptographic key specified by the ANSI X9 TR-31 standard.*&lt;br/&gt;- **TR34: TR34**  : *Format of a cryptographic key specified by the ANSI X9 TR-34 standard.*&lt;br/&gt;- **I238: ISO20038KeyWrap**  : *Format of a cryptographic key specified by the ISO20038 standard.*&lt;br/&gt;
   * @return encryptionFormat
  **/
  @Schema(description = "Format of data before encryption, if the format is not plaintext or implicit.<br/>- **TR31: TR31**  : *Format of a cryptographic key specified by the ANSI X9 TR-31 standard.*<br/>- **TR34: TR34**  : *Format of a cryptographic key specified by the ANSI X9 TR-34 standard.*<br/>- **I238: ISO20038KeyWrap**  : *Format of a cryptographic key specified by the ISO20038 standard.*<br/>")
  public Object getEncryptionFormat() {
    return encryptionFormat;
  }

  public void setEncryptionFormat(Object encryptionFormat) {
    this.encryptionFormat = encryptionFormat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter poipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter = (PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter) o;
    return Objects.equals(this.bytePadding, poipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter.bytePadding) &&
        Objects.equals(this.initialisationVector, poipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter.initialisationVector) &&
        Objects.equals(this.encryptionFormat, poipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter.encryptionFormat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bytePadding, initialisationVector, encryptionFormat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardDataEnvelopedDataEncryptedContentContentEncryptionAlgorithmParameter {\n");
    
    sb.append("    bytePadding: ").append(toIndentedString(bytePadding)).append("\n");
    sb.append("    initialisationVector: ").append(toIndentedString(initialisationVector)).append("\n");
    sb.append("    encryptionFormat: ").append(toIndentedString(encryptionFormat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
