/*
 * nexo retailer API
 * API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: romain.loreal@lorealconsulting.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lorealconsulting.nexoRetailerAPI.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lorealconsulting.nexoRetailerAPI.client.model.PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardData;
import com.lorealconsulting.nexoRetailerAPI.client.model.PoipoiIdfinancialServiceServiceRequestLoyaltyRequestTransactionOriginalPOITransactionTransactionDetailsCurrencyConversionResultConversion;
import com.lorealconsulting.nexoRetailerAPI.client.model.SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponseAuthorisationResult;
import com.lorealconsulting.nexoRetailerAPI.client.model.SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponseBalance;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Authorisation response from the acquirer.&lt;br/&gt;
 */
@Schema(description = "Authorisation response from the acquirer.<br/>")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-09T14:21:17.741236018+02:00[Europe/Paris]")

public class SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse {
  @SerializedName("Action")
  private Object action = null;

  @SerializedName("AdditionalAvailableProduct")
  private Object additionalAvailableProduct = null;

  @SerializedName("AllowedProductCode")
  private Object allowedProductCode = null;

  @SerializedName("AuthorisationResult")
  private SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponseAuthorisationResult authorisationResult = null;

  @SerializedName("Balance")
  private SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponseBalance balance = null;

  @SerializedName("CurrencyConversionEligibility")
  private PoipoiIdfinancialServiceServiceRequestLoyaltyRequestTransactionOriginalPOITransactionTransactionDetailsCurrencyConversionResultConversion currencyConversionEligibility = null;

  @SerializedName("NotAllowedProductCode")
  private Object notAllowedProductCode = null;

  @SerializedName("ProtectedBalance")
  private PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardData protectedBalance = null;

  public SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse action(Object action) {
    this.action = action;
    return this;
  }

   /**
   * Set of actions to be performed by the POI (Point Of Interaction) system.
   * @return action
  **/
  @Schema(description = "Set of actions to be performed by the POI (Point Of Interaction) system.")
  public Object getAction() {
    return action;
  }

  public void setAction(Object action) {
    this.action = action;
  }

  public SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse additionalAvailableProduct(Object additionalAvailableProduct) {
    this.additionalAvailableProduct = additionalAvailableProduct;
    return this;
  }

   /**
   * Products that may be added to the purchase after the authorisation.
   * @return additionalAvailableProduct
  **/
  @Schema(description = "Products that may be added to the purchase after the authorisation.")
  public Object getAdditionalAvailableProduct() {
    return additionalAvailableProduct;
  }

  public void setAdditionalAvailableProduct(Object additionalAvailableProduct) {
    this.additionalAvailableProduct = additionalAvailableProduct;
  }

  public SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse allowedProductCode(Object allowedProductCode) {
    this.allowedProductCode = allowedProductCode;
    return this;
  }

   /**
   * Product code which are allowed by the payment card.
   * @return allowedProductCode
  **/
  @Schema(description = "Product code which are allowed by the payment card.")
  public Object getAllowedProductCode() {
    return allowedProductCode;
  }

  public void setAllowedProductCode(Object allowedProductCode) {
    this.allowedProductCode = allowedProductCode;
  }

  public SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse authorisationResult(SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponseAuthorisationResult authorisationResult) {
    this.authorisationResult = authorisationResult;
    return this;
  }

   /**
   * Get authorisationResult
   * @return authorisationResult
  **/
  @Schema(required = true, description = "")
  public SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponseAuthorisationResult getAuthorisationResult() {
    return authorisationResult;
  }

  public void setAuthorisationResult(SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponseAuthorisationResult authorisationResult) {
    this.authorisationResult = authorisationResult;
  }

  public SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse balance(SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponseBalance balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @Schema(description = "")
  public SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponseBalance getBalance() {
    return balance;
  }

  public void setBalance(SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponseBalance balance) {
    this.balance = balance;
  }

  public SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse currencyConversionEligibility(PoipoiIdfinancialServiceServiceRequestLoyaltyRequestTransactionOriginalPOITransactionTransactionDetailsCurrencyConversionResultConversion currencyConversionEligibility) {
    this.currencyConversionEligibility = currencyConversionEligibility;
    return this;
  }

   /**
   * Get currencyConversionEligibility
   * @return currencyConversionEligibility
  **/
  @Schema(description = "")
  public PoipoiIdfinancialServiceServiceRequestLoyaltyRequestTransactionOriginalPOITransactionTransactionDetailsCurrencyConversionResultConversion getCurrencyConversionEligibility() {
    return currencyConversionEligibility;
  }

  public void setCurrencyConversionEligibility(PoipoiIdfinancialServiceServiceRequestLoyaltyRequestTransactionOriginalPOITransactionTransactionDetailsCurrencyConversionResultConversion currencyConversionEligibility) {
    this.currencyConversionEligibility = currencyConversionEligibility;
  }

  public SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse notAllowedProductCode(Object notAllowedProductCode) {
    this.notAllowedProductCode = notAllowedProductCode;
    return this;
  }

   /**
   * Product code not allowed by the payment card.
   * @return notAllowedProductCode
  **/
  @Schema(description = "Product code not allowed by the payment card.")
  public Object getNotAllowedProductCode() {
    return notAllowedProductCode;
  }

  public void setNotAllowedProductCode(Object notAllowedProductCode) {
    this.notAllowedProductCode = notAllowedProductCode;
  }

  public SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse protectedBalance(PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardData protectedBalance) {
    this.protectedBalance = protectedBalance;
    return this;
  }

   /**
   * Get protectedBalance
   * @return protectedBalance
  **/
  @Schema(description = "")
  public PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardData getProtectedBalance() {
    return protectedBalance;
  }

  public void setProtectedBalance(PoipoiIdfinancialServiceServiceRequestEnvironmentCardProtectedCardData protectedBalance) {
    this.protectedBalance = protectedBalance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse saleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse = (SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse) o;
    return Objects.equals(this.action, saleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse.action) &&
        Objects.equals(this.additionalAvailableProduct, saleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse.additionalAvailableProduct) &&
        Objects.equals(this.allowedProductCode, saleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse.allowedProductCode) &&
        Objects.equals(this.authorisationResult, saleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse.authorisationResult) &&
        Objects.equals(this.balance, saleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse.balance) &&
        Objects.equals(this.currencyConversionEligibility, saleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse.currencyConversionEligibility) &&
        Objects.equals(this.notAllowedProductCode, saleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse.notAllowedProductCode) &&
        Objects.equals(this.protectedBalance, saleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse.protectedBalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, additionalAvailableProduct, allowedProductCode, authorisationResult, balance, currencyConversionEligibility, notAllowedProductCode, protectedBalance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaleToPOIServiceResponseV06ServiceResponsePaymentResponseRetailerPaymentResultTransactionResponse {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    additionalAvailableProduct: ").append(toIndentedString(additionalAvailableProduct)).append("\n");
    sb.append("    allowedProductCode: ").append(toIndentedString(allowedProductCode)).append("\n");
    sb.append("    authorisationResult: ").append(toIndentedString(authorisationResult)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    currencyConversionEligibility: ").append(toIndentedString(currencyConversionEligibility)).append("\n");
    sb.append("    notAllowedProductCode: ").append(toIndentedString(notAllowedProductCode)).append("\n");
    sb.append("    protectedBalance: ").append(toIndentedString(protectedBalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
