# coding: utf-8

"""
    nexo retailer API

    API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: romain.loreal@lorealconsulting.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'identification': 'PoipoiIdfinancialServiceHeaderInitiatingParty',
        'parameters_version': 'object'
    }

    attribute_map = {
        'identification': 'Identification',
        'parameters_version': 'ParametersVersion'
    }

    def __init__(self, identification=None, parameters_version=None):  # noqa: E501
        """PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer - a model defined in Swagger"""  # noqa: E501
        self._identification = None
        self._parameters_version = None
        self.discriminator = None
        if identification is not None:
            self.identification = identification
        if parameters_version is not None:
            self.parameters_version = parameters_version

    @property
    def identification(self):
        """Gets the identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer.  # noqa: E501


        :return: The identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer.  # noqa: E501
        :rtype: PoipoiIdfinancialServiceHeaderInitiatingParty
        """
        return self._identification

    @identification.setter
    def identification(self, identification):
        """Sets the identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer.


        :param identification: The identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer.  # noqa: E501
        :type: PoipoiIdfinancialServiceHeaderInitiatingParty
        """

        self._identification = identification

    @property
    def parameters_version(self):
        """Gets the parameters_version of this PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer.  # noqa: E501

        Specifies a character string with a maximum length of 256 characters.<br/>  # noqa: E501

        :return: The parameters_version of this PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer.  # noqa: E501
        :rtype: object
        """
        return self._parameters_version

    @parameters_version.setter
    def parameters_version(self, parameters_version):
        """Sets the parameters_version of this PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer.

        Specifies a character string with a maximum length of 256 characters.<br/>  # noqa: E501

        :param parameters_version: The parameters_version of this PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer.  # noqa: E501
        :type: object
        """

        self._parameters_version = parameters_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoipoiIdfinancialServiceServiceRequestEnvironmentAcquirer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
