# coding: utf-8

"""
    nexo retailer API

    API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: romain.loreal@lorealconsulting.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'approval_code_length': 'object',
        'card_capture_capable': 'object',
        'card_reading_capabilities': 'object',
        'cardholder_verification_capabilities': 'object',
        'message_capabilities': 'object',
        'max_script_length': 'object',
        'on_line_capabilities': 'object',
        'pin_length_capabilities': 'object'
    }

    attribute_map = {
        'approval_code_length': 'ApprovalCodeLength',
        'card_capture_capable': 'CardCaptureCapable',
        'card_reading_capabilities': 'CardReadingCapabilities',
        'cardholder_verification_capabilities': 'CardholderVerificationCapabilities',
        'message_capabilities': 'MessageCapabilities',
        'max_script_length': 'MaxScriptLength',
        'on_line_capabilities': 'OnLineCapabilities',
        'pin_length_capabilities': 'PINLengthCapabilities'
    }

    def __init__(self, approval_code_length=None, card_capture_capable=None, card_reading_capabilities=None, cardholder_verification_capabilities=None, message_capabilities=None, max_script_length=None, on_line_capabilities=None, pin_length_capabilities=None):  # noqa: E501
        """PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities - a model defined in Swagger"""  # noqa: E501
        self._approval_code_length = None
        self._card_capture_capable = None
        self._card_reading_capabilities = None
        self._cardholder_verification_capabilities = None
        self._message_capabilities = None
        self._max_script_length = None
        self._on_line_capabilities = None
        self._pin_length_capabilities = None
        self.discriminator = None
        if approval_code_length is not None:
            self.approval_code_length = approval_code_length
        if card_capture_capable is not None:
            self.card_capture_capable = card_capture_capable
        if card_reading_capabilities is not None:
            self.card_reading_capabilities = card_reading_capabilities
        if cardholder_verification_capabilities is not None:
            self.cardholder_verification_capabilities = cardholder_verification_capabilities
        if message_capabilities is not None:
            self.message_capabilities = message_capabilities
        if max_script_length is not None:
            self.max_script_length = max_script_length
        if on_line_capabilities is not None:
            self.on_line_capabilities = on_line_capabilities
        if pin_length_capabilities is not None:
            self.pin_length_capabilities = pin_length_capabilities

    @property
    def approval_code_length(self):
        """Gets the approval_code_length of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501

        Number of objects represented as a positive integer.<br/>  # noqa: E501

        :return: The approval_code_length of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :rtype: object
        """
        return self._approval_code_length

    @approval_code_length.setter
    def approval_code_length(self, approval_code_length):
        """Sets the approval_code_length of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.

        Number of objects represented as a positive integer.<br/>  # noqa: E501

        :param approval_code_length: The approval_code_length of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :type: object
        """

        self._approval_code_length = approval_code_length

    @property
    def card_capture_capable(self):
        """Gets the card_capture_capable of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501

        A flag indicating a True or False value.<br/>  # noqa: E501

        :return: The card_capture_capable of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :rtype: object
        """
        return self._card_capture_capable

    @card_capture_capable.setter
    def card_capture_capable(self, card_capture_capable):
        """Sets the card_capture_capable of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.

        A flag indicating a True or False value.<br/>  # noqa: E501

        :param card_capture_capable: The card_capture_capable of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :type: object
        """

        self._card_capture_capable = card_capture_capable

    @property
    def card_reading_capabilities(self):
        """Gets the card_reading_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501

        Card reading capabilities of the POI (Point Of Interaction) performing the transaction.  # noqa: E501

        :return: The card_reading_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :rtype: object
        """
        return self._card_reading_capabilities

    @card_reading_capabilities.setter
    def card_reading_capabilities(self, card_reading_capabilities):
        """Sets the card_reading_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.

        Card reading capabilities of the POI (Point Of Interaction) performing the transaction.  # noqa: E501

        :param card_reading_capabilities: The card_reading_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :type: object
        """

        self._card_reading_capabilities = card_reading_capabilities

    @property
    def cardholder_verification_capabilities(self):
        """Gets the cardholder_verification_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501

        Cardholder verification capabilities of the POI (Point Of Interaction) performing the transaction.  # noqa: E501

        :return: The cardholder_verification_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :rtype: object
        """
        return self._cardholder_verification_capabilities

    @cardholder_verification_capabilities.setter
    def cardholder_verification_capabilities(self, cardholder_verification_capabilities):
        """Sets the cardholder_verification_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.

        Cardholder verification capabilities of the POI (Point Of Interaction) performing the transaction.  # noqa: E501

        :param cardholder_verification_capabilities: The cardholder_verification_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :type: object
        """

        self._cardholder_verification_capabilities = cardholder_verification_capabilities

    @property
    def message_capabilities(self):
        """Gets the message_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501

        Capabilities of the terminal to display or print message to the cardholder and the merchant.  # noqa: E501

        :return: The message_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :rtype: object
        """
        return self._message_capabilities

    @message_capabilities.setter
    def message_capabilities(self, message_capabilities):
        """Sets the message_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.

        Capabilities of the terminal to display or print message to the cardholder and the merchant.  # noqa: E501

        :param message_capabilities: The message_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :type: object
        """

        self._message_capabilities = message_capabilities

    @property
    def max_script_length(self):
        """Gets the max_script_length of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501

        Number of objects represented as a positive integer.<br/>  # noqa: E501

        :return: The max_script_length of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :rtype: object
        """
        return self._max_script_length

    @max_script_length.setter
    def max_script_length(self, max_script_length):
        """Sets the max_script_length of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.

        Number of objects represented as a positive integer.<br/>  # noqa: E501

        :param max_script_length: The max_script_length of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :type: object
        """

        self._max_script_length = max_script_length

    @property
    def on_line_capabilities(self):
        """Gets the on_line_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501

        On-line and off-line capabilities of the POI (Point Of Interaction).<br/>- **OFLN: OffLine**  : *Off-line only capable.*<br/>- **ONLN: OnLine**  : *On-line only capable.*<br/>- **SMON: SemiOffLine**  : *Off-line capable with possible on-line requests to the acquirer.*<br/>  # noqa: E501

        :return: The on_line_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :rtype: object
        """
        return self._on_line_capabilities

    @on_line_capabilities.setter
    def on_line_capabilities(self, on_line_capabilities):
        """Sets the on_line_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.

        On-line and off-line capabilities of the POI (Point Of Interaction).<br/>- **OFLN: OffLine**  : *Off-line only capable.*<br/>- **ONLN: OnLine**  : *On-line only capable.*<br/>- **SMON: SemiOffLine**  : *Off-line capable with possible on-line requests to the acquirer.*<br/>  # noqa: E501

        :param on_line_capabilities: The on_line_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :type: object
        """

        self._on_line_capabilities = on_line_capabilities

    @property
    def pin_length_capabilities(self):
        """Gets the pin_length_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501

        Number of objects represented as a positive integer.<br/>  # noqa: E501

        :return: The pin_length_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :rtype: object
        """
        return self._pin_length_capabilities

    @pin_length_capabilities.setter
    def pin_length_capabilities(self, pin_length_capabilities):
        """Sets the pin_length_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.

        Number of objects represented as a positive integer.<br/>  # noqa: E501

        :param pin_length_capabilities: The pin_length_capabilities of this PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities.  # noqa: E501
        :type: object
        """

        self._pin_length_capabilities = pin_length_capabilities

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoipoiIdfinancialServiceServiceRequestEnvironmentPOICapabilities):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
