# coding: utf-8

"""
    nexo retailer API

    API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: romain.loreal@lorealconsulting.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'provider_identification': 'object',
        'requestor_identification': 'object'
    }

    attribute_map = {
        'provider_identification': 'ProviderIdentification',
        'requestor_identification': 'RequestorIdentification'
    }

    def __init__(self, provider_identification=None, requestor_identification=None):  # noqa: E501
        """PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor - a model defined in Swagger"""  # noqa: E501
        self._provider_identification = None
        self._requestor_identification = None
        self.discriminator = None
        self.provider_identification = provider_identification
        self.requestor_identification = requestor_identification

    @property
    def provider_identification(self):
        """Gets the provider_identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor.  # noqa: E501

        Specifies a character string with a maximum length of 35 characters.<br/>  # noqa: E501

        :return: The provider_identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor.  # noqa: E501
        :rtype: object
        """
        return self._provider_identification

    @provider_identification.setter
    def provider_identification(self, provider_identification):
        """Sets the provider_identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor.

        Specifies a character string with a maximum length of 35 characters.<br/>  # noqa: E501

        :param provider_identification: The provider_identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor.  # noqa: E501
        :type: object
        """
        if provider_identification is None:
            raise ValueError("Invalid value for `provider_identification`, must not be `None`")  # noqa: E501

        self._provider_identification = provider_identification

    @property
    def requestor_identification(self):
        """Gets the requestor_identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor.  # noqa: E501

        Specifies a character string with a maximum length of 35 characters.<br/>  # noqa: E501

        :return: The requestor_identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor.  # noqa: E501
        :rtype: object
        """
        return self._requestor_identification

    @requestor_identification.setter
    def requestor_identification(self, requestor_identification):
        """Sets the requestor_identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor.

        Specifies a character string with a maximum length of 35 characters.<br/>  # noqa: E501

        :param requestor_identification: The requestor_identification of this PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor.  # noqa: E501
        :type: object
        """
        if requestor_identification is None:
            raise ValueError("Invalid value for `requestor_identification`, must not be `None`")  # noqa: E501

        self._requestor_identification = requestor_identification

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoipoiIdfinancialServiceServiceRequestEnvironmentMerchantTokenTokenRequestor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
