# coding: utf-8

"""
    nexo retailer API

    API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: romain.loreal@lorealconsulting.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sale_to_poi_service_response_v06_service_response_reversal_response import SaleToPOIServiceResponseV06ServiceResponseReversalResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestSaleToPOIServiceResponseV06ServiceResponseReversalResponse(unittest.TestCase):
    """SaleToPOIServiceResponseV06ServiceResponseReversalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaleToPOIServiceResponseV06ServiceResponseReversalResponse(self):
        """Test SaleToPOIServiceResponseV06ServiceResponseReversalResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sale_to_poi_service_response_v06_service_response_reversal_response.SaleToPOIServiceResponseV06ServiceResponseReversalResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
