# coding: utf-8

"""
    nexo retailer API

    API defining resources for interactions between POI and POS, using underlying nexo messages  ### Check out its awesome features:  * simply declare POS and POI * send requests to POI * monitor activity 😎 * Receive real-time information about transaction executions📈   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: romain.loreal@lorealconsulting.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sale_to_poi_service_request_v06 import SaleToPOIServiceRequestV06  # noqa: E501
from swagger_client.rest import ApiException


class TestSaleToPOIServiceRequestV06(unittest.TestCase):
    """SaleToPOIServiceRequestV06 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaleToPOIServiceRequestV06(self):
        """Test SaleToPOIServiceRequestV06"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sale_to_poi_service_request_v06.SaleToPOIServiceRequestV06()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
